# -*- coding: utf-8 -*-
"""Atividade 3 - Cecília Ionara.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RBBDTr8BWfp39TC4RrY6HpDkY-2hu15

Cecília Ionara Pinheiro de Araújo
"""

##1.1. Faça um somatório simples. A função a ser somada e a quantidade de repetições são de sua
##escolha.

soma = 0
i = 1

for i in range(1, 11):
    soma += i

print("A soma dos elementos de 1 a 10 é:", soma)

##1.2. Faça um somatório apenas com números pares. Altere a forma de passagem dos números
##(por exemplo, usando incremento de 2 no for).

soma = 0
i = 0

for i in range(2,10,2):
  soma += i

print("A soma dos elementos de 1 a 10 seleionando apenas os pares é:", soma)

##2.1 Crie um programa que calcule o número fatorial de um número informado pelo usuário.

f = int(input("Informe o número: "))
r = f

for i in range(f - 1):
    r *= (f - 1 - i)

print(f"O fatorial de {f} é {r}")

#3. Solicite um número de notas e depois calcule e mostre a média. Dica: use input() e a função
#float().
#3.1. Além da média, informe também a maior nota. Dica: use if.

maiorNota = 0
notas = []
qt = int(input("Informe o número de notas que deseja inserir: "))

for i in range(qt):
    n = float(input(f"Informe a nota {i+1}: "))
    notas.append(n)
    if n > maiorNota:
        maiorNota = n

media = sum(notas) / qt

print(f"A média das notas é {media:.2f}")
print(f"A maior nota é {maiorNota}")

##1. Solicite informações de um aluno repetidamente. O programa deve encerrar quando for
##digitado "FIM". Dica: use input().

n = ""

while n != "FIM":
    nome = input("Informe o nome do aluno: ")
    nota = float(input("Informe a nota do aluno: "))
    print(f"Aluno: {nome}, Nota: {nota}")

    n = input("Digite 'FIM' para encerrar ou pressione Enter para continuar: ")

print("Programa encerrado!")

##2. Crie um menu que se repete até o usuário escolher uma opção válida. Dica: utilize print() para
##exibir um menu e input() para receber a escolha.

opcao = ""

while opcao not in [1, 2, 3]:
  print("---------- MENU ----------")
  print("1 - Arroz, feijão e carne")
  print("2 - Macarrão, salada e frango")
  print("3 - Grão de bico, salada e batata")

  opcao = int(input("Selecione a opção desejada: "))

  if opcao not in [1, 2, 3]:
    print("Opção inválida!! Selecione um número entre 1 e 3\n")

print("Opção válida! Seu pedido está em produção.")