# -*- coding: utf-8 -*-
"""Desafio03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYwpIcFCE0iHfXoOUL-r9sQ0k5NBHf3g

Cecília Ionara Pinheiro de Araújo
"""

votos = {
    1: 0,  # Sofia
    2: 0,  # Domingues
    3: 0,  # Pedro
    4: 0,  # Carlos
    5: 0,  # Helena
    6: 0,  # Larissa
    "branco": 0,
    "nulo": 0
}

def conta_votos(voto):
    if voto in votos:
        votos[voto] += 1
    elif voto == 0:
        votos["branco"] += 1
    else:
        votos["nulo"] += 1

print("-- MENU --")
print("1 - Sofia")
print("2 - Domingues")
print("3 - Pedro")
print("4 - Carlos")
print("5 - Helena")
print("6 - Larissa")
print("0 - Voto em branco")
print("Outro número - Voto nulo")

while True:
    print("\nOlá! Bem-vindo à votação")
    voto = int(input("Digite o número correspondente ao seu candidato: "))
    conta_votos(voto)

    opcao = input("Deseja continuar votando? (S para sim / N para não): ").upper()
    if opcao == 'N':
        break

print("\nResultados da eleição...")
print(f"Sofia: {votos[1]} votos")
print(f"Domingues: {votos[2]} votos")
print(f"Pedro: {votos[3]} votos")
print(f"Carlos: {votos[4]} votos")
print(f"Helena: {votos[5]} votos")
print(f"Larissa: {votos[6]} votos")
print(f"Branco: {votos['branco']} votos")
print(f"Nulo: {votos['nulo']} votos")