# -*- coding: utf-8 -*-
"""Desafio 02 - Cecília Ionara.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101AtlB41Pxy1lQenm1ZHZqEEEkhOClJ5

Cecília Ionara Pinheiro de Araújo
"""

import math

def adicao():
    a = float(input("Digite o primeiro número: "))
    b = float(input("Digite o segundo número: "))
    print(f"Resultado: {a + b}")

def subtracao():
    a = float(input("Digite o primeiro número: "))
    b = float(input("Digite o segundo número: "))
    print(f"Resultado: {a - b}")

def multiplicacao():
    a = float(input("Digite o primeiro número: "))
    b = float(input("Digite o segundo número: "))
    print(f"Resultado: {a * b}")

def divisao():
    a = float(input("Digite o primeiro número: "))
    b = float(input("Digite o segundo número: "))
    print(f"Resultado: {a / b}")

def exponenciacao():
    base = float(input("Digite a base: "))
    expoente = float(input("Digite o expoente: "))
    print(f"Resultado: {base ** expoente}")

def raiz_quadrada():
    numero = float(input("Digite um número: "))
    if numero < 0:
        print("Erro: raiz quadrada de número negativo!")
    else:
        print(f"Resultado: {math.sqrt(numero)}")

def bhaskara():
    print("Equação no formato: ax² + bx + c = 0")
    a = float(input("Digite o valor de a: "))
    b = float(input("Digite o valor de b: "))
    c = float(input("Digite o valor de c: "))

    if a == 0:
        print("Não é uma equação de segundo grau.")
        return

    delta = b ** 2 - 4 * a * c
    print(f"Delta = {delta}")

    if delta < 0:
        print("Não existem raízes reais.")
    elif delta == 0:
        x = -b / (2 * a)
        print(f"Raiz única: x = {x}")
    else:
        x1 = (-b + math.sqrt(delta)) / (2 * a)
        x2 = (-b - math.sqrt(delta)) / (2 * a)
        print(f"Duas raízes reais: x1 = {x1}, x2 = {x2}")

def mostrar_menu():
    print("\n=== CALCULADORA CIENTÍFICA ===")
    print("1. Adição")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")
    print("5. Exponenciação")
    print("6. Raiz quadrada")
    print("7. Bhaskara (Equação de 2º grau)")
    print("8. Sair")

def main():
    while True:
        mostrar_menu()
        escolha = input("Escolha uma opção: ")

        match escolha:
            case "1":
                adicao()
            case "2":
                subtracao()
            case "3":
                multiplicacao()
            case "4":
                divisao()
            case "5":
                exponenciacao()
            case "6":
                raiz_quadrada()
            case "7":
                bhaskara()
            case "8":
                print("Saindo da calculadora...")
                break
            case _:
                print("Opção inválida. Tente novamente.")

main()